sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t monsterlee0911/react-test -f ./client/Dockerfile.dev ./client
    - 
script:
    - docker run -e CI=true monsterlee0911/react-test npm test

after_success:
    - docker build -t monsterlee0911/multi-client ./client
    - docker build -t monsterlee0911/multi-nginx ./nginx
    - docker build -t monsterlee0911/multi-server ./server
    - docker build -t monsterlee0911/multi-worker ./worker
    
    # Log in docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push monsterlee0911/multi-client
    - docker push monsterlee0911/multi-nginx
    - docker push monsterlee0911/multi-worker
    - docker push monsterlee0911/multi-server